trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projects: '**/*.csproj'
  testProjects: '**/*Tests/*.csproj'
  clientApp: 'outagemap.client'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '22.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(projects)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(projects)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- script: mkdir -p "$HOME/.aspnet/https"
  displayName: 'Create HTTPS certificate directory'

- script: npm ci
  workingDirectory: '$(clientApp)'
  displayName: 'npm install'

- script: npm run lint
  workingDirectory: '$(clientApp)'
  displayName: 'npm lint'

- script: npm run build
  workingDirectory: '$(clientApp)'
  displayName: 'npm build'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '$(testProjects)'
    arguments: '--configuration $(buildConfiguration) --no-build'