// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using ReactApp1.Server.Models;

#nullable disable

namespace ReactApp1.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReactApp1.Server.Models.DirectionsResponseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DirectionsResponseEntities");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.DisplayRouteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DisplayRouteEntities");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.RouteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectionsResponseId")
                        .HasColumnType("int");

                    b.Property<double?>("Distance")
                        .HasColumnType("float");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<LineString>("Geometry")
                        .HasColumnType("geography");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<string>("WeightName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DirectionsResponseId");

                    b.ToTable("RouteEntity");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.RouteLegEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<int>("RouteEntityId")
                        .HasColumnType("int");

                    b.Property<int>("RouteEntityRouteId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RouteEntityId");

                    b.ToTable("RouteLegEntity");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.WaypointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectionsResponseEntityId")
                        .HasColumnType("int");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.PrimitiveCollection<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RouteEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectionsResponseEntityId");

                    b.HasIndex("RouteEntityId");

                    b.ToTable("WaypointEntity");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.RouteEntity", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.DirectionsResponseEntity", "DirectionsResponse")
                        .WithMany("RouteEntities")
                        .HasForeignKey("DirectionsResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectionsResponse");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.RouteLegEntity", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.RouteEntity", "RouteEntity")
                        .WithMany("Legs")
                        .HasForeignKey("RouteEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteEntity");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.WaypointEntity", b =>
                {
                    b.HasOne("ReactApp1.Server.Models.DirectionsResponseEntity", null)
                        .WithMany("WaypointEntities")
                        .HasForeignKey("DirectionsResponseEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReactApp1.Server.Models.RouteEntity", "RouteEntity")
                        .WithMany()
                        .HasForeignKey("RouteEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RouteEntity");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.DirectionsResponseEntity", b =>
                {
                    b.Navigation("RouteEntities");

                    b.Navigation("WaypointEntities");
                });

            modelBuilder.Entity("ReactApp1.Server.Models.RouteEntity", b =>
                {
                    b.Navigation("Legs");
                });
#pragma warning restore 612, 618
        }
    }
}
